name: Topic Branch Build & Test

on:
  push:
    branches:
      - 'feature-*'  # triggers only on branches starting with "feature-"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image (but don’t push)
      run: |
        docker build -t secretshare:test .

    - name: Run tests
      run: |
        pytest
